name: rpi-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add libs
      run: sudo apt-get install -y libi2c-dev
    - name: make all
      run: make all
